// All user-facing text in one place. No em dashes in description strings.
export const COPY = {
  team: {
    title: "IronBee",
    connectedTitle: "Connected to IronBee",
    connectedText: (accountName: string | null) =>
      accountName ? `This team reports to the IronBee account "${accountName}".` : "This team is connected to an IronBee account.",
    notConnectedTitle: "Connect this team to IronBee",
    notConnectedText:
      "IronBee opens every deploy preview in a real browser and tests it like a user. Connect the team to your IronBee account, then turn verification on per project.",
    connectButton: "Connect to IronBee",
    connectPending: "Preparing your link...",
    openConsole: "Open IronBee settings",
    linkReadyTitle: "Finish in IronBee",
    linkReadyText: "The link opens IronBee in a new tab. Sign in (or create an account) and choose the account this team belongs to, then come back here.",
    openLink: "Open IronBee",
    refresh: "I have connected, refresh",
    disconnect: "Disconnect",
    disconnectHelp: "Stops verification for every project on this team. Deploy notifications IronBee created are removed on the next delivery.",
    errorTitle: "Something went wrong",
  },
  site: {
    title: "IronBee verification",
    teamNotConnected: "This team is not connected to IronBee yet. Open the extension's team configuration to connect it first.",
    disabledText:
      "Turn on verification and IronBee will test every deploy preview and branch deploy of this project. Production deploys are skipped.",
    enable: "Turn on verification",
    enabledText: "Verification is on. Each deploy preview and branch deploy is opened in a real browser and tested; the result appears on the pull request and on the deploy page.",
    disable: "Turn off verification",
    contextsTitle: "Which deploys",
    contextPreview: "Deploy previews",
    contextBranch: "Branch deploys",
    contextProduction: "Production deploys",
    hookOk: "Deploy notification is active.",
    hookPaused: "Netlify paused the deploy notification after repeated failures. Resume it to keep receiving verifications.",
    hookMissing: "The deploy notification is missing on Netlify. Turn verification off and on again to recreate it.",
    resume: "Resume notification",
    protectionTitle: "Preview access",
    protectionText:
      "If this project's previews are password protected, IronBee needs credentials to get in. Add them in IronBee under Settings, then Integrations. Public previews need nothing.",
    protectionOpen: "Open preview access settings",
    lastEvent: (iso: string | null) => (iso ? `Last deploy notification: ${new Date(iso).toLocaleString()}` : "No deploy notification received yet."),
    previewsMadePublic: "Deploy previews of this project were private; they are now public so IronBee can open them. Production was already public and is unchanged.",
    previewsPrivateAll:
      "This project is private (production and previews). IronBee cannot open private previews, and making previews public also makes production public on Netlify. Choose one:",
    makePublic: "Make the project public",
    makePublicHelp: "Production and previews become reachable by anyone with the link.",
    privateAlternative: "Or, on a Pro plan, switch the project to a password and add the password to IronBee under Settings, then Integrations.",
    previewsPublicOk: "Previews are public; IronBee can open them.",
    passwordProtected: "This project is password protected. Add the password to IronBee under Settings, then Integrations, so the agent can get in.",
    madePublicTitle: "Project is now public",
    errorTitle: "Something went wrong",
  },
  deploy: {
    title: "IronBee verification",
    notEnabled: "Verification is not turned on for this project. Enable it in the project's IronBee panel.",
    noJob: "IronBee has not verified this deploy. Only deploy previews and branch deploys are verified, and only after the deploy went live.",
    running: "IronBee is verifying this deploy in a real browser...",
    passed: "Verified: no issues found.",
    failed: "Verified: issues found.",
    inconclusive: "IronBee could not reach a verdict for this deploy.",
    cancelled: "The verification was cancelled.",
    openSession: "Open the session in IronBee",
    issuesTitle: "Issues",
  },
} as const;
